### PR TITLE
Fix links on SA blog post

### PR DESCRIPTION
**Pull request by rgaiacs**
Screenshot of blog post with links not well formatted

screencapture-datacarpentry-org-blog-sa-partner-1484950416918

Screenshot of same blog post with pull request applied

screencapture-localhost-4000-blog-sa-partner-1484950400729

@tracykteal or @ErinBecker can you merge this pull request?

### CODE REVIEW

**Comment by ErinBecker** [comment]
Thanks @rgaiacs!

**Comment by ErinBecker** [comment]
@rgaiacs After I merged, the links didn't work properly. I reverted and tried to fix the links another way. Does it look ok on your end?

**Comment by rgaiacs** [comment]
@ErinBecker They now look like

screencapture-datacarpentry-org-blog-sa-partner-1484953714536

it is better than before

screencapture-datacarpentry-org-blog-sa-partner-1484950416918

since now we have something more like a list. But the `[` and `]` around the URL don't like good to me. If @anelda desires was to have a "academic reference list" we can remove the `[` and `]` around the URL. I thought that she intended to have the tail of the file as the URLs to the links since many times [we forget](https://github.com/gvwilson/instructor-training/pull/3) the `:` between the reference and the URL and end up with the the outcome that I saw in the first place but since the text had `[foo]` instead of `[foo](reference-key)` I opted to replace `[foo]` with `[[foo](foo)]` to have the link inside the `[]`. Looking more careful now, I noticed that https://github.com/datacarpentry/datacarpentry.github.io/pull/197/files has

~~~
In November 2014 the [first large-scale Software Carpentry event was run in South Africa](https://software-carpentry.org/blog/2014/12/cape-town-swc.html) [1] as part ...
~~~

and

~~~
[1] [https://software-carpentry.org/blog/2014/12/cape-town-swc.html]
~~~

so I believe that @anelda wanted to have

~~~
In November 2014 the [first large-scale Software Carpentry event was run in South Africa](1) as part ...
~~~

and

~~~
[1]: https://software-carpentry.org/blog/2014/12/cape-town-swc.html
~~~

since the URL are the same. We should wait @anelda told us what is the correct version. **Sorry for all the trouble.**

**Comment by anelda** [comment]
Hi @rgaiacs @ErinBecker! Apologies for making so much work for you :-). I am happy either way. Whatever makes sense here. Please go ahead with what you proposed.  Thanks!

**Pull request merged**
