### PR TITLE
added Belinda to people page

### PR DESCRIPTION
**Pull request by tracykteal**

### CODE REVIEW

**Comment by tracykteal** [comment]
I'm not quite sure that it will render OK, but @weaverbel could you check content.

**Comment by weaverbel** [comment]
Hi @tracykteal - the info seems fine but the picture looks slightly enormous. I will resize it and send you a smaller version.

**Comment by tracykteal** [comment]
updated with the smaller picture

**Comment by ErinBecker** [comment]
@tracykteal I merged this but then reverted it because there were a few problems. See https://github.com/datacarpentry/datacarpentry.github.io/pull/253.

I expected reverting to reopen the original PR, but it didn't. Sorry.

**Comment by tracykteal** [comment]
Thanks @ErinBecker. I have some local rendering issues that conflict with this html page, so I'll touch base with you about it.

**Pull request merged**
