### PR TITLE
add Spanish python lesson

### PR DESCRIPTION
**Pull request by raynamharris**
I'm not exactly sure the best way to add the new Spanish python lesson to this page. This PR adds it to the table with all the other Ecology lessons, placing it just underneath the English version. 

It could also make sense to make a whole other Spanish section somewhere or use a different means to emphasize it within the Ecology section.

### CODE REVIEW

**Comment by ErinBecker** [comment]
Good question @raynamharris. For the SWC lessons, we have them listed in a separate lesson table below all of the English lessons, but you're right that that might not make sense for DC since there are already multiple lesson tables. What about including the Spanish lessons for a given curriculum as a separate table *within* the appropriate curriculum section. So the Ecology section would have one table titled "Lessons in English" and then another one titles "Lessons in Spanish" with this lesson listed in the same table format. 

It would be great to also add the note about the workshop template and lesson template being available in Spanish (like in the SWC lesson table): 

The lesson template and the workshop template are available in Spanish. If you are interested in getting involved with our Spanish lessons contact us. (with links)

La la plantilla de lección y la plantilla de taller están disponibles en español. Si está interesado en participar en nuestra lección de español contáctenos. (with links)

Would you mind adding that here? Once we have Spanish lessons for other curricula (outside of Ecology), we can move that note to the main body of the page rather than just the Ecology section.

**Comment by ErinBecker** [comment]
@raynamharris - I'd like to also note that this lesson is in *beta* as it hasn't been taught several times in Spanish yet. So the title should be in the format of "Data Management with SQL for Social Scientists *beta*".

Have you gotten someone on staff to run checks for formatting consistency? If not, please let me know and I can plan on doing that near the end of December (I'm about to go on vacation or would do it now - it's a really exciting lesson!).

**Comment by ErinBecker** [comment]
@fmichonneau - I'll be on vacation for a week. Could you check the PR (not the formatting of the whole lesson) when @raynamharris updates it and merge if it looks good to you?

**Comment by maneesha** [comment]
@ErinBecker  @fmichonneau @raynamharris 
Is this ready to merge?

**Comment by raynamharris** [comment]
I haven't had a chance to look into @ErinBecker's comments and suggestions, so no, not quite ready for merge.

**Comment by raynamharris** [comment]
Now it's ready for review @maneesha and @ErinBecker

**Comment by maneesha** [comment]
Thanks @raynamharris .

@ErinBecker  - do you want to review this before merging?

**Comment by fmichonneau** [comment]
it looks good to me!

**Pull request merged**
