### PR TITLE
Create 2017-07-27-bug-bbq.md

### PR DESCRIPTION
**Pull request by weaverbel**
Not merging till I have run it by Erin

### CODE REVIEW

**Comment by weaverbel** [comment]
Hi @ErinBecker I have done a first draft but it is very light on actual detail. Is there an etherpad for signing up for the Bug BBQ? Something with local times etc and links to the work needed?

**Comment by ErinBecker** [comment]
@weaverbel - Not yet - would you like me to put one together? I'm teaching today but I can probably get to it during lunch break.

**Comment by weaverbel** [comment]
@ErinBecker It can wait - I know what it's like trying to do this while teaching ;-( I am just drip feeding date claimers through Twitter and we can post the link tomorrow. Good luck with the teaching.

**Comment by ErinBecker** [comment]
@weaverbel I added a link to the Etherpad with timing information and a checklist of help needed. I'll go ahead and merge. Thanks for putting this together! Really helpful!

**Pull request merged**
