### PR TITLE
Create 2017-04-24-UPRtraining.md

### PR DESCRIPTION
**Pull request by raynamharris**
Blog post about instructor training in Puerto Rico. Also posted on SWC website at  https://github.com/swcarpentry/website/pull/700

### CODE REVIEW

**Comment by tracykteal** [comment]
Could you change the file name to 2017-04-24...

**Comment by raynamharris** [comment]
date adjusted @tracykteal

**Comment by tracykteal** [comment]
It looks like the file is still _posts/2014-04-24-UPRtraining.md  Since github/Jekyll uses the date for ordering, could you change it to _posts/2017-04-24-UPRtraining.md  A 'git mv _posts/2014-04-24-UPRtraining.md _posts/2017-04-24-UPRtraining.md' should fix it. Thanks!

**Comment by raynamharris** [comment]
I have never used the command line for this repo before... May I delete this PR and submit a new one with a proper file name instead of using git?

**Comment by tracykteal** [comment]
Yes, that would work just as well. Thank you!

**Pull request closed without merging**
