### PR TITLE
Create 2016-12-06-genomics-nwu blog post

### PR DESCRIPTION
**Pull request by anelda**

### CODE REVIEW

**Comment by ErinBecker** [comment]
@anelda This looks great and actually aligns perfectly with one of the new blog series we're working on about building local communities. I was actually planning on asking you to write one of those, but it looks like you beat me to the punch!

Would you mind if I promoted this as an edition in that series? We have another post in the series scheduled for this Friday, and I'd like to try to keep the scheduling consistent so that folks know what to expect on the blog. Would you mind if I waited to merge this until next Friday (the 16th?). If you'd rather get it out sooner, I understand. Please let me know and thanks for sharing!

**Comment by anelda** [comment]
Thanks for the positive feedback! Ideally we'd like to publish this as we
want to refer to it when in the post about our new partnership with SWC/DC.
Apogies for messing with the schedule :-). We could always do a follow up
in a few months time to give feedback abt progress?

I am happy for this to go out as part of the series thanks.

**Comment by ErinBecker** [comment]
@anelda No problem! How about we post this tomorrow as an introduction to the series, with a follow-up from our other contributor on Friday. We'd love to have another follow-up from you in a few months talking about your progress. Could you suggest a date for me to put on the calendar?

**Comment by anelda** [comment]
Hi Erin

Thanks that sounds terrific.

Hmmm.... somewhere in May? Maybe after the 10th?

Thanks. I like you series blog posts a lot!

Kind regards,

Anelda

**Comment by ErinBecker** [comment]
Thanks Anelda, I put you down for Friday May 12th, but I'll send a reminder and we can finalize the date as we get closer!

**Pull request merged**
