### PR TITLE
Blog post about DDA hire

### PR DESCRIPTION
**Pull request by ErinBecker**
Blog post about new Deputy Director of Assessment.

### CODE REVIEW

**Comment by ErinBecker** [comment]
@tracykteal Let me know if this looks good and I'll go ahead and merge.

**Comment by gvwilson** [comment]
Please ping me when it's merged and I'll do a cross-referral from the 
SWC site.

**Comment by tracykteal** [comment]
Set up email, and checking that it works.

**Comment by ErinBecker** [comment]
W00T!

**Pull request merged**
