### PR TITLE
updated lessons page with lessons under development

### PR DESCRIPTION
**Pull request by tracykteal**
Updated lessons page with different sections for teaching and under development/consideration

Needs links to email lists before merging.

@maneesha comments for clarity for people looking for information on lessons
@ErinBecker things seem accurate?

### CODE REVIEW

**Comment by maneesha** [comment]
I'd suggest moving the biology semester long section to the bottom, or somehow make it clear that it's not something that we really offer.  That is, someone can't contact us and ask us to run a semester long program.  However it is available if people want to use it themselves.

**Comment by maneesha** [comment]
All the under development sections (social sciences, digital humanities, etc) say sign up for mailing list but that link goes to github repo

**Comment by maneesha** [comment]
Can we also link to Reproducible Research lesson set?

**Comment by maneesha** [comment]
All this said I'm really glad to see these updates being put in to place.  I was planning on bringing this up at our weekly meeting so it's good to see it's already in the works.

**Comment by tracykteal** [comment]
Thanks. I'll add the Reproducible Research under 'under development' and move the semester long materials to the end. Maybe I'll add some contact info there too.

Links will go to the mailing lists once they're set up.

**Comment by ErinBecker** [comment]
This looks really good to me, especially after the proposed changes from @maneesha. I really like the idea of having the status of each of the materials clearly laid out so that people know what is on the horizon. Thanks for putting this together @tracykteal. Let me know if you'd like me to review again and merge after you make the updates.

**Comment by ErinBecker** [comment]
@tracykteal - Is this ready to merge?

**Comment by tracykteal** [comment]
I updated this PR based on comments, moving the semester materials below the other workshop ones, adding in the email links and adding the link to the 'lesson-ideas' repo.

**Comment by ErinBecker** [comment]
LGTM, thanks for putting this together @tracykteal!

**Pull request merged**
