### PR TITLE
Update /people/ with bios.

### PR DESCRIPTION
**Pull request by ErinBecker**

### CODE REVIEW

**Comment by ErinBecker** [comment]
@tracykteal @maneesha @hlapp @karthik @gvwilson @kcranston @apawlik @ethanwhite Please take a look at new bios. Most are compiled from Linkedin profiles, Twitter blurbs, and personal homepages. If you notice anything out-dated or would like to make changes, please let me know. I'll hold off on merging till this weekend unless I hear from everyone before then.

**Comment by kcranston** [comment]
Looks good to me. Thanks, @ErinBecker !

**Comment by maneesha** [comment]
Mine is good.

**Comment by apawlik** [comment]
@ErinBecker Thanks for this! Just a correction for mine (which is my fault because I have't replied to your emails!): "Aleksandra Pawlik works at the New Zealand eScience Infrastructure[www.nesi.org.nz] where she coordinates training for research communities."

**Comment by ErinBecker** [comment]
Thanks @apawlik! I knew you had moved, but wasn't sure of the new org. Should be correct now.

**Pull request merged**
