### PR TITLE
Created page for mentoring program

### PR DESCRIPTION
**Pull request by kariljordan**
@ErinBecker 
Testing to see if this page will be under the dropdown "For Instructors".

### CODE REVIEW

**Comment by ErinBecker** [comment]
Looks good to me. Thanks @kariljordan!

**Comment by kariljordan** [comment]
Any idea where the page is located on our website? I checked all the dropdown menus and can’t find the Mentoring page I created.

**Comment by ErinBecker** [comment]
It's here: http://www.datacarpentry.org/mentoring/

If you want it to be included in a dropdown, you need to add it to the page navigation file here: https://github.com/datacarpentry/datacarpentry.github.io/blob/master/_data/navigation.yml

**Comment by tracykteal** [comment]
There's also a SWC Mentoring subcommittee page. 

https://software-carpentry.org/join/subcom/mentoring/

I'm not sure if any information needs to be synched.

**Comment by kariljordan** [comment]
I asked @weaverbel to copy the info about mentoring groups from DC's mentoring page and add it to the SWC mentoring page, then we'll be all set.

**Comment by weaverbel** [comment]
And I will do that @kariljordan @tracykteal @ErinBecker but it probably won't be till Thursday - the SWC page has a lot of info pulled in from elsewhere so it is a lot more fiddly than just adding a chunk in - I have to suss out where best to put it so it renders properly. Will get to it as soon as I can.

**Pull request merged**
