### PR TITLE
Create 2018-04-26-dc-seven-weeks.md

### PR DESCRIPTION
**Pull request by weaverbel**
Ready to merge - UF workshop reportback

### CODE REVIEW

**Comment by sdtaylor** [comment]
Thanks a bunch for putting this into markdown. Looks good to me :+1:

**Comment by tracykteal** [comment]
Thanks so much @sdtaylor and others. This is a great post. I'll merge this Friday (US) morning and get it out on Twitter too.

**Comment by weaverbel** [comment]
Can this be merged @tracykteal ?

**Comment by tracykteal** [comment]
Sorry for the delay. I didn't want to get this up on a Friday, so was waiting to merge. I'll merge now and we'll get it out on Twitter today and tomorrow. Thank you!

**Pull request merged**
