### PR TITLE
added blog post or RRHack Jupyter curriculum hackathon

### PR DESCRIPTION
**Pull request by tracykteal**
Confirm with authors that this is ok to post 

@hlapp @fmichonneau ok to post with you as authors?

### CODE REVIEW

**Comment by fmichonneau** [comment]
yes, it looks good to me. Thanks!

**Comment by tracykteal** [comment]
Not on purpose. I can change that. Wasn't sure if we should include affiliation or not. I don't think we necessarily need to, but having them shows it's a joint effort.

**Comment by kellieotto** [comment]
I would just change Jasmine's and my affiliations -- we are not technically affiliated with Jupyter, but with BIDS.

**Comment by tracykteal** [comment]
Thanks @kellieotto. Would it be OK if I just took affiliations out? I'm realizing it will start to get sort of long, because many of us also have multiple affiliations.

**Comment by hlapp** [comment]
> Would it be OK if I just took affiliations out?

That'd be fine with me. They are stated in the full CfP anyway, so this does sound a bit redundant. Unless normally all your blog post authors are always given with affiliation. (And even then it should be Duke University for me, not RRhack 😃

**Comment by kellieotto** [comment]
Also fine with me.

**Comment by tracykteal** [comment]
Thanks all. Affiliations removed and posted.

**Pull request merged**
