### PR TITLE
carpentrycon blog post

### PR DESCRIPTION
**Pull request by tracykteal**
Added CarpentryCon blog post

### CODE REVIEW

**Comment by tracykteal** [comment]
We need to add the form for people to answer if they want to attend. So hold on merging until this is added.

**Comment by weaverbel** [comment]
Didn't see this had been posted and created my own so this one can close as I have merged mine with the form in it.

**Comment by rgaiacs** [comment]
https://github.com/datacarpentry/datacarpentry.github.io/pull/320 is related with this.

**Comment by tracykteal** [comment]
Closing, because Belinda put in another one that's now live.

**Pull request closed without merging**
